#include "portList.h"

const int portTcp[] = {
	PORT_FTP,
	PORT_SSH,
	PORT_TELNET,
	PORT_SMTP,
	PORT_DNS,
	PORT_HTTP,
	PORT_KERBEROS,
	PORT_RPC,
	PORT_NETBIOS_SSN,
	PORT_LDAP,
	PORT_HTTPS,
	PORT_SMB,
	PORT_MSSQL,
	PORT_ORACLEDB,
	PORT_FTP_ALT,
	PORT_SSH_ALT,
	PORT_HTTP_GRAFANA,
	PORT_MYSQL,
	PORT_RDP,
	PORT_DNS_ALT,
	PORT_POSTGRESQL,
	//PORT_VNC,
	PORT_WINRM,
	//PORT_VNC,
	PORT_HTTP_PORTAINER,
	PORT_HTTP_TOMCAT,
	PORT_HTTP_PROXY,
	PORT_HTTP_OTHER,
	PORT_HTTP_DELUGE,
	PORT_HTTPS_PORTAINER,
	PORT_HTTP_PROMETHEUS,
};
/*

#define PORT_UDP_DNS	53
#define PORT_UDP_DHCP	67
#define PORT_UDP_DHCP	68
#define PORT_UDP_NTP	123
#define PORT_UDP_SNMP	161
#define PORT_UDP_SNMP	162

67, 68	Dynamic Host Configuration Protocol (DHCP)
*/
const int portUdp[] = {
	PORT_UDP_NETBIOS,
	PORT_UDP_DHCP,
	PORT_UDP_DHCP2,
	PORT_UDP_NTP,
	PORT_UDP_SNMP,
	PORT_UDP_SNMP2,
};